package Controllers;

import Inputs.KeyboardInputs;
import Models.Car;
import Models.Picture;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Double.max;
import static java.lang.Math.random;
import static java.lang.Math.max;
import static java.lang.Math.min;
import java.util.LinkedList;
import javax.swing.JOptionPane;



/**
 *
 * @author Santi
 */
public class GamePanel extends javax.swing.JPanel{
    
    private int frames = 0;
    private long lastCheck = 0;
    
    /**
     * Creates new form Canvas
     */
    public GamePanel() {
        addKeyListener(new KeyboardInputs(this));
        setPanelSize();
        
    }
    
    private void setPanelSize() {
        Dimension size = new Dimension(1280, 720);
        setMinimumSize(size);
        setPreferredSize(size);
        setMaximumSize(size);
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Picture p = new Car("src/Images/playerCar.png", false, 640, 600, 100, 100);
                      //Car(String url, boolean machine, int x, int y, int height, int width)
        draw(g, p);
        
    }
    
    public void draw(Graphics p, Picture i) {
        Toolkit t = Toolkit.getDefaultToolkit();
        Image pic = t.getImage(i.getUrl());
        p.drawImage(pic, i.getX(), i.getY(), i.getWidth(), i.getHeight(), this);     
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
